### ISSUE TITLE
мелочь по БЭМ

### ISSUE THREAD

**Issue by cjbars** [darik97/webapp_5semester#2]
у вас есть активный пункт меню с такими стилями
```
<li class="header__item header__active">Start</li>
```

правильнее будет применить модификатор ```header__item-active```
ведь это пункт меню выделяется а не header, верно?

**Comment by darik97** [comment]
https://github.com/darik97/webapp_5semester/commit/9c7b90de56be079d957d20bec18dac942e7e4786
